--- 
- name: Creating SSM directory  in tmp
  file:
    path: "{{ temp_ssm }}"
    state: directory
  
- name: Install rpm file for Redhat Family (Amazon Linux, RHEL, and CentOS) 32/64-bit
  become: yes
  yum:
    name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install deb file for Debian family 32/64-bit
  apt:
    deb: "https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb"
  when: ansible_os_family == 'Debian'

- name: "start and enable SSM - REDHAT"
   systemd: name={{ item }} state=started enabled=yes
   with_items:
      - amazon-ssm-agent
        
- name: "Register to service - Debian"
   service:
    name: amazon-ssm-agent
    enabled: yes
    state: started
    when: ansible_os_family == 'Debian'

- name: test services
    command: systemctl status {{ item }}
    with_items:
      - amazon-ssm-agent
    ignore_errors: yes
    register: services_state
      
- name: Debug
   debug:
   var: services_state
   
- name: Report status of SSM Agent
    fail:
    msg: |
      Service SSM is not running.
      Output of `systemctl status amazon-ssm-agent`:
      {{ service_amazon-ssm-agent_status.stdout }}
      {{ service_amazon-ssm-agent_status.stderr }}
    when: service_amazon-ssm-agent_status | failed
