--- 
- name: Creating SSM directory  in tmp
  file:
    path: /tmp/ssm
    state: directory
  
- name: Install rpm file for Redhat Family (Amazon Linux, RHEL, and CentOS) 32/64-bit
  yum:
    name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    state: present
  when: ansible_os_family == 'RedHat'

- name: Install deb file for Debian family 32/64-bit
  apt:
    deb: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
    state: present
  when: ansible_os_family == 'Debian'
        
- name: "Register to service - Debian"
  service: name={{ item}} state=started enabled=yes
  with_items:
    - amazon-ssm-agent

- name: status services
  command: systemctl status {{ item }}
  with_items:
    - amazon-ssm-agent
  ignore_errors: yes
  register: services_state
      
