---
- ec2_instance_facts:
    region: us-east-1
    filters:
      "tag:MaintainanceWindow": 3rdMon6pm
  register: instanceId
- debug: var=instanceId.instances[1].instance_id

- name: Patching Group
  ec2_tag:
    #aws_access_key: "{{ aws_access_key }}"
    #aws_secret_key: "{{ aws_secret_key }}"
    region: us-east-1
    resource: "{{ instanceId.instances[1].instance_id }}"
    state: present
    tags:
      env_patch: prod_patch
